dist: xenial
language: node_js
node_js:
  - "11"
services:
  - mongodb
addons:
  apt:
    packages:
      - rabbitmq-server
before_install:
  - curl -O https://raw.githubusercontent.com/codex-team/hawk.registry/master/config/rabbit.definitions.json
  - rabbitmqadmin -q import rabbit.definitions.json
  - chmod +x ./bin/env-config.sh
  - ./bin/env-config.sh
  - yarn add global jest codecov
install:
  - yarn install
script:
  - yarn lint
  - jest --coverage && codecov
