dist: xenial
language: node_js
node_js:
  - "11"
services:
  - mongodb
  - rabbitmq
before_install:
  - chmod +x ./bin/env-config.sh
  - ./bin/env-config.sh
  - yarn add global jest codecov
install:
  - yarn install
script:
  - yarn lint
  - jest --coverage && codecov
