/**
 * File is auto-generated by scripts/generateTemplatesNames.ts
 */
enum Templates {
  Assignee = 'assignee',
  BlockWorkspace = 'block-workspace',
  NewEvent = 'new-event',
  PaymentFailed = 'payment-failed',
  SeveralEvents = 'several-events',
}

export default Templates;
