/**
 * File is auto-generated by scripts/generateTemplatesNames.ts
 */
enum Templates {
  Assignee = 'assignee',
  NewEvent = 'new-event',
  SeveralEvents = 'several-events',
}

export default Templates;
