/**
 * File is auto-generated by scripts/generateTemplatesNames.ts
 */
enum Templates {
  Assignee = 'assignee',
  BlockWorkspace = 'block-workspace',
  DaysLimitReached = 'days-limit-reached',
  Event = 'event',
  PaymentFailed = 'payment-failed',
  PaymentSuccess = 'payment-success',
  SeveralEvents = 'several-events',
}

export default Templates;
