/**
 * Script to generate enum with template names
 *
 * To provide type-safe template names, this script reads template directories' names and generate TS enum
 *
 * Run `yarn generate-tpl-names` any time you add new template
 *
 * Example:
 *
 * - templates
 *   - new-event
 *   - several-events
 *
 * Output enum:
 * enum Templates {
 *   NewEvent = 'new-event',
 *   SeveralEvents = 'several-events'
 * }
 */
import * as path from 'path';
import * as fs from 'fs';

/**
 * Function format dir name in kebab-case to PascalCase for enum
 *
 * @param name - file name to transform
 */
function formatName(name: string): string {
  return name
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

/**
 * This folder contains available emails templates
 */
const emailTemplatesDir = 'src/templates/emails';

/**
 * Path to email templates folder
 */
const emailTemplatesPath = path.resolve(__dirname, '..', emailTemplatesDir);

/**
 * Read template dir names
 */
const names = fs.readdirSync(emailTemplatesPath);

/**
 * Enum file content
 */
let generatedEnum = '/**\n * File is auto-generated by scripts/generateTemplatesNames.ts\n */\n';

generatedEnum += 'enum Templates {\n';
generatedEnum += names.map((name: string) => `  ${formatName(name)} = '${name}',`).join('\n');
generatedEnum += '\n}\n\nexport default Templates;\n';

fs.writeFileSync('../src/templates/names.ts', generatedEnum);
